import { describe, expect, it } from 'vitest'
import { MANUFACTURING_FORMULAS, advanceManufacturing, authorizeManufacturingBatch, collectManufacturing, droneBaseMinutes, nextManufacturingEvent, quoteManufacturingStart, replaceManufacturingFormula, startManufacturing, updateManufacturingCapacity } from './manufacturingTimeline'

const started = (formula: keyof typeof MANUFACTURING_FORMULAS, capacityWeight = 54) => startManufacturing({ formula, capacityWeight, paymentAuthorized: true })
describe('manufacturing timeline', () => {
  it('uses raw timing and weights at an integer completion boundary', () => { const state=started('exp-medium'); expect(state.remainingBaseMinutes).toBe(180); expect(state.formula.storageWeight).toBe(5); expect(nextManufacturingEvent(state)).toBe(180); const r=advanceManufacturing(state,180); expect(r.completedItems).toBe(1); expect(r.state.storedWeight).toBe(5); expect(r.state.awaitingPayment).toBe(true) })
  it('preserves a partial batch and returns surplus base work after one discrete completion', () => { const partial=advanceManufacturing(started('gold'),71); expect(partial.state.remainingBaseMinutes).toBe(1); const r=advanceManufacturing(partial.state,145); expect(r.completedBatches).toBe(1); expect(r.state.pendingItems).toBe(1); expect(r.state.remainingBaseMinutes).toBe(72); expect(r.unusedBaseMinutes).toBe(144) })
  it('requires explicit external approval and exposes the costs before each shard start', () => { const waiting=startManufacturing({formula:'fragment-orirock',capacityWeight:54,paymentAuthorized:false}); expect(advanceManufacturing(waiting,60).unusedBaseMinutes).toBe(60); expect(quoteManufacturingStart('fragment-orirock')).toEqual([{id:'30012',count:2,type:'MATERIAL'},{id:'4001',count:1600,type:'GOLD'}]); const approved=authorizeManufacturingBatch(waiting,true); expect(approved.started).toBe(true); expect(advanceManufacturing(approved.state,60).completedItems).toBe(1) })
  it('routes drone base work through the same single-batch boundary', () => { const natural=advanceManufacturing(started('gold'),69); const drone=advanceManufacturing(natural.state,droneBaseMinutes(1)); expect(drone.completedItems).toBe(1); expect(droneBaseMinutes(4)).toBe(12) })
  it('blocks the next batch at full storage and resumes only after collect and authorization', () => { const complete=advanceManufacturing(started('gold',2),72); const blocked=authorizeManufacturingBatch(complete.state,true); expect(blocked.started).toBe(false); expect(blocked.state.blockedByStorage).toBe(true); expect(nextManufacturingEvent(blocked.state)).toBeNull(); const collected=collectManufacturing(blocked.state); const resumed=authorizeManufacturingBatch(collected.state,true); expect(resumed.started).toBe(true); expect(advanceManufacturing(resumed.state,72).completedItems).toBe(1) })
  it('keeps stored products when live capacity falls below them and blocks another batch', () => { const complete=advanceManufacturing(started('gold',4),72); const reduced=updateManufacturingCapacity(complete.state,1); expect(reduced.storedWeight).toBe(2); const batch=authorizeManufacturingBatch(reduced,true); expect(batch.started).toBe(false); expect(batch.state.blockedByStorage).toBe(true) })
  it('keeps the two source shard recipes distinct and refuses implicit formula changes', () => { expect(quoteManufacturingStart('fragment-device')).toEqual([{id:'30062',count:1,type:'MATERIAL'},{id:'4001',count:1000,type:'GOLD'}]); const state=advanceManufacturing(started('gold'),20).state; expect(replaceManufacturingFormula(state,'exp-medium').diagnostics).toEqual(['FORMULA_CHANGE_REQUIRES_EXPLICIT_RESET']) })
})
