import { describe, expect, it } from 'vitest'
import { createDefaultConfig } from '../domain/defaults'
import { OPERATORS } from '../domain/operators'
import { evaluateOperators } from './operatorRules'

const id = (name: string) => OPERATORS.find(o => o.name === name)!.charId
function setup(names: string[], level: 1 | 2 | 3 = 3) {
  const config = createDefaultConfig()
  config.controlOperatorIds = []
  config.rooms.forEach(r => { r.operatorIds = [] })
  const room = config.rooms.find(r => r.type === 'trading')!
  room.level = level
  room.operatorIds = names.map(id)
  room.specialOrder = 'none'
  return { room, config }
}

// Highest-phase Jaye has BOTH independent skills. With legal queue Q <= L,
// 4*(L-Q)+4*Q = 4*L. No expected value is generated by the implementation.
// Base capacities 6/8/10: catalog.building.tradingData.phases[].orderLimit.
describe('highest-phase Jaye queue-independent static audit', () => {
  it.each([[1, 125], [2, 133], [3, 141]])('single Jaye at level %i has total %i', (level, total) => {
    const { room, config } = setup(['孑'], level as 1 | 2 | 3)
    const result = evaluateOperators(room, config)
    expect(result.efficiencyPercent).toBe(total)
    expect(result.unquantifiedSkills).not.toContain('孑·摊贩经济')
    expect(result.unquantifiedSkills).not.toContain('孑·市井之道')
  })
  it('applies a teammate efficiency before reducing capacity', () => {
    const { room, config } = setup(['孑', '能天使'])
    expect(evaluateOperators(room, config).efficiencyPercent).toBe(165) // 100+2+35+4*(10-3)
  })
  it('includes positive capacity before Jaye reduction', () => {
    const { room, config } = setup(['孑', '银灰', '崖心'])
    expect(evaluateOperators(room, config).efficiencyPercent).toBe(198) // 100+3+35+4*(10+4+4-3)
  })
  it('does not include central room-wide Amiya bonus in Jaye capacity loss', () => {
    const { room, config } = setup(['孑', '能天使'])
    config.controlOperatorIds = [id('阿米娅')]
    expect(evaluateOperators(room, config).efficiencyPercent).toBe(172) // previous 165+7
  })
  it('keeps Snowsant alone at zero skill efficiency', () => {
    const { room, config } = setup(['雪雉'])
    expect(evaluateOperators(room, config).efficiencyPercent).toBe(101)
  })
  it('does not copy Jaye alone into Snowsant: cc.t.strong2', () => {
    const { room, config } = setup(['孑', '雪雉'])
    expect(evaluateOperators(room, config).efficiencyPercent).toBe(142) // 100+2+40+0
  })
  it('counts Snowsant copying a third operator before Jaye capacity loss', () => {
    const { room, config } = setup(['孑', '雪雉', '能天使'])
    expect(evaluateOperators(room, config).efficiencyPercent).toBe(185) // 100+3+35+35+4*(10-7)
  })
  it('handles a third operator below the Snowsant cap', () => {
    const { room, config } = setup(['孑', '雪雉', '银灰'])
    expect(evaluateOperators(room, config).efficiencyPercent).toBe(183) // 100+3+20+20+4*(10+4-4)
  })
  it('Shamare clears the complete Jaye contribution', () => {
    const { room, config } = setup(['孑', '巫恋'])
    expect(evaluateOperators(room, config).efficiencyPercent).toBe(147) // 100+2+45
  })
  it('Shamare clears Jaye and an ordinary third teammate', () => {
    const { room, config } = setup(['孑', '巫恋', '能天使'])
    expect(evaluateOperators(room, config).efficiencyPercent).toBe(193) // 100+3+90
  })
  it('Gnosis applies per-Kjerag penalty and capacity before Jaye: observed 125 skill points', () => {
    const { room, config } = setup(['孑', '银灰', '崖心'])
    config.controlOperatorIds = [id('灵知')]
    expect(evaluateOperators(room, config).efficiencyPercent).toBe(228)
    // SilverAsh 20-15=5; Cliffheart 15-15=0; capacity 10+4+4+6+6=30;
    // floor(5/10)=0; Jaye 120; 100+3+5+120=228.
  })
  it('exhausted Jaye provides neither efficiency nor capacity reduction', () => {
    const { room, config } = setup(['孑', '能天使'])
    config.zeroMoraleOperatorIds = [id('孑')]
    expect(evaluateOperators(room, config).efficiencyPercent).toBe(136)
  })
})

import { evaluateHighestPhaseJaye, type HighestPhaseJayeInput } from './jayeRules'

const helperInput = (partners: HighestPhaseJayeInput['partners'] = []): HighestPhaseJayeInput => ({
  roomLevel: 3, hasBothJayeSkills: true, partners,
})

describe('pure highest-phase Jaye integration helper', () => {
  it('matches the observed Gnosis SilverAsh Cliffheart 125-skill-point combination', () => {
    const result = evaluateHighestPhaseJaye(helperInput([
      { operatorId: id('银灰'), efficiency: 5, orderLimitDelta: 10, snowsantCopyableEfficiency: 5 },
      { operatorId: id('崖心'), efficiency: 0, orderLimitDelta: 10, snowsantCopyableEfficiency: 0 },
    ]))
    expect(result).toMatchObject({ supported: true, jayeEfficiency: 120, otherEfficiency: 5, effectiveOrderLimit: 30 })
  })
  it.each([0, 1, 5, 10])('does not vary with legal queue count %i', queuedOrders => {
    expect(evaluateHighestPhaseJaye({ ...helperInput(), queuedOrders })).toMatchObject({ supported: true, jayeEfficiency: 40 })
  })
  it('resolves the source-defined Snowsant third-partner ordering', () => {
    const result = evaluateHighestPhaseJaye({ ...helperInput([
      { operatorId: id('能天使'), efficiency: 35, orderLimitDelta: 0, snowsantCopyableEfficiency: 35 },
    ]), snowsant: { operatorId: id('雪雉'), cap: 35 } })
    expect(result).toMatchObject({ supported: true, jayeEfficiency: 12, snowsantEfficiency: 35, effectiveOrderLimit: 3 })
  })
  it('does not let Snowsant recursively copy Jaye', () => {
    expect(evaluateHighestPhaseJaye({ ...helperInput(), snowsant: { operatorId: id('雪雉'), cap: 35 } }))
      .toMatchObject({ supported: true, jayeEfficiency: 40, snowsantEfficiency: 0 })
  })
  it('supports partner with order-limit conversion skill where order-limit bonus does not reduce Jaye capacity', () => {
    expect(evaluateHighestPhaseJaye(helperInput([
      { operatorId: id('琳琅诗怀雅'), efficiency: 20, orderLimitDelta: 0, snowsantCopyableEfficiency: 20, dependsOnOrderLimit: true },
    ]))).toMatchObject({ supported: true, jayeEfficiency: 32, effectiveOrderLimit: 8, capacityReduction: 2 })
  })
  it('reports negative efficiency as unverified', () => {
    expect(evaluateHighestPhaseJaye(helperInput([
      { operatorId: id('初雪'), efficiency: -15, orderLimitDelta: 6, snowsantCopyableEfficiency: -15 },
    ]))).toMatchObject({ supported: false, reason: 'JAYE_NEGATIVE_EFFICIENCY_UNVERIFIED' })
  })
  it('rejects over-capacity transient queues without disguising them as ordinary state', () => {
    expect(evaluateHighestPhaseJaye({ ...helperInput(), queuedOrders: 11 }))
      .toMatchObject({ supported: false, reason: 'JAYE_QUEUE_EXCEEDS_EFFECTIVE_LIMIT' })
  })
  it('never treats first-skill-only Jaye as highest-phase Jaye', () => {
    expect(evaluateHighestPhaseJaye({ ...helperInput(), hasBothJayeSkills: false }))
      .toMatchObject({ supported: false, reason: 'JAYE_REQUIRES_BOTH_ACTIVE_SKILLS' })
  })
  it('clearing produces zero efficiency without claiming resolved live capacity', () => {
    expect(evaluateHighestPhaseJaye({ ...helperInput(), clearedByShamare: true }))
      .toMatchObject({ supported: true, jayeEfficiency: 0, snowsantEfficiency: 0, effectiveOrderLimit: null })
  })
  it('deducts only base efficiency when orderLimitDerivedEfficiency is provided', () => {
    const result = evaluateHighestPhaseJaye(helperInput([
      { operatorId: id('琳琅诗怀雅'), efficiency: 60, orderLimitDelta: 0, snowsantCopyableEfficiency: 60, dependsOnOrderLimit: true, orderLimitDerivedEfficiency: 40 },
    ]))
    // Base efficiency is 60 - 40 = 20, capacityReduction is floor(20/10) = 2.
    // effectiveOrderLimit is 10 - 2 = 8, Jaye gets 8 * 4 = 32%.
    expect(result).toMatchObject({
      supported: true,
      jayeEfficiency: 32,
      effectiveOrderLimit: 8,
      capacityReduction: 2,
      otherEfficiency: 20,
    })
  })
})

describe('Elite 0 Jaye shift-run evaluation', () => {
  it('supports Elite 0 Jaye without partner capacity deduction under shift-run', () => {
    const result = evaluateHighestPhaseJaye({
      ...helperInput([
        { operatorId: id('能天使'), efficiency: 35, orderLimitDelta: 0, snowsantCopyableEfficiency: 35 },
      ]),
      hasBothJayeSkills: false,
      isElite0: true,
    })
    expect(result).toMatchObject({
      supported: true,
      jayeEfficiency: 40,
      snowsantEfficiency: 0,
      effectiveOrderLimit: 10,
      capacityReduction: 0,
      otherEfficiency: 35,
    })
  })

  it('applies partner order limit bonus directly to Elite 0 Jaye efficiency without capacity penalty', () => {
    const result = evaluateHighestPhaseJaye({
      ...helperInput([
        { operatorId: id('银灰'), efficiency: 20, orderLimitDelta: 4, snowsantCopyableEfficiency: 20 },
        { operatorId: id('崖心'), efficiency: 15, orderLimitDelta: 4, snowsantCopyableEfficiency: 15 },
      ]),
      hasBothJayeSkills: false,
      isElite0: true,
    })
    // 10 base + 4 + 4 = 18 limit, capacityReduction = 0. Jaye: 18 * 4 = 72%.
    expect(result).toMatchObject({
      supported: true,
      jayeEfficiency: 72,
      snowsantEfficiency: 0,
      effectiveOrderLimit: 18,
      capacityReduction: 0,
      otherEfficiency: 35,
    })
  })

  it('supports Snowsant copying partner efficiency under Elite 0 Jaye without reducing capacity', () => {
    const result = evaluateHighestPhaseJaye({
      ...helperInput([
        { operatorId: id('能天使'), efficiency: 35, orderLimitDelta: 0, snowsantCopyableEfficiency: 35 },
      ]),
      snowsant: { operatorId: id('雪雉'), cap: 35 },
      hasBothJayeSkills: false,
      isElite0: true,
    })
    expect(result).toMatchObject({
      supported: true,
      jayeEfficiency: 40,
      snowsantEfficiency: 35,
      effectiveOrderLimit: 10,
      capacityReduction: 0,
      otherEfficiency: 70,
    })
  })

  it('deducts queued orders from Elite 0 Jaye efficiency when queuedOrders is specified', () => {
    const result = evaluateHighestPhaseJaye({
      ...helperInput([
        { operatorId: id('能天使'), efficiency: 35, orderLimitDelta: 0, snowsantCopyableEfficiency: 35 },
      ]),
      hasBothJayeSkills: false,
      isElite0: true,
      queuedOrders: 3,
    })
    // limit 10, queue 3 -> diff 7 -> jayeEfficiency 28%
    expect(result).toMatchObject({
      supported: true,
      jayeEfficiency: 28,
      effectiveOrderLimit: 10,
      capacityReduction: 0,
    })
  })

  it('evaluates Elite 0 Jaye under config.jayeElite0 = true with Exusiai, gaining +12% over Elite 1', () => {
    const { room, config } = setup(['孑', '能天使'])
    config.jayeElite0 = true
    const result = evaluateOperators(room, config)
    expect(result.efficiencyPercent).toBe(177) // 100 + 2 (staff) + 35 (Exusiai) + 40 (Jaye)
    expect(result.unquantifiedSkills).toEqual([])
  })

  it('evaluates Elite 0 Jaye under config.jayeElite0 = true with SilverAsh and Cliffheart, gaining +12% over Elite 1', () => {
    const { room, config } = setup(['孑', '银灰', '崖心'])
    config.jayeElite0 = true
    const result = evaluateOperators(room, config)
    expect(result.efficiencyPercent).toBe(210) // 100 + 3 (staff) + 35 (SA+Cliff) + 72 (Jaye)
    expect(result.unquantifiedSkills).toEqual([])
  })

  it('evaluates Elite 0 Jaye with Snowsant and Exusiai, gaining +28% over Elite 1', () => {
    const { room, config } = setup(['孑', '雪雉', '能天使'])
    config.jayeElite0 = true
    const result = evaluateOperators(room, config)
    expect(result.efficiencyPercent).toBe(213) // 100 + 3 + 35 + 35 + 40
    expect(result.unquantifiedSkills).toEqual([])
  })

  it('automatically evaluates Jaye as Elite 0 when Jaye in operatorRecords only has the first skill unlocked', async () => {
    const { room, config } = setup(['孑', '能天使'])
    const { compileOperatorInventory } = await import('../domain/operatorInventory')
    const { inventoryOperatorRecords } = await import('../domain/operatorContext')
    config.operatorRecords = inventoryOperatorRecords(compileOperatorInventory([
      { operator: '孑', elitePhase: 0, level: 1 },
      { operator: '能天使', elitePhase: 2, level: 1 },
    ]))
    const result = evaluateOperators(room, config)
    expect(result.efficiencyPercent).toBe(177)
    expect(result.unquantifiedSkills).toEqual([])
  })
})

